const allMenu = {};
let js = 77381;
let pizzahut = 50666;
let mcD = 81940;
let bgW = 90461;
let newModernCafe = 34829;
let gajananVp = 379063;
let ssd = 447796;
let chineseWok = 403973;
let rajusPizzaCorner = 329272;
let ramdevPureVeg = 73828;
let burgerKing = 513069;
let momoNation = 572069;
let thakurVp = 29591;
let appetiteMomo = 233838;
let behrouzBiryani=59244

allMenu[js] = {
  Beverages: [
    {
      id: "22034331",
      name: "Masala Tea",
      category: "Beverages",
      description:
        "Masala tea is a beverage ,masala tea is a beverage made by simmering spices with milk & tea.",
      inStock: 1,
      isVeg: 1,
      price: 2000,
      variants: {},
      variantsV2: {},
      itemAttribute: {
        vegClassifier: "VEG",
      },
      ribbon: {},
      type: "ITEM",
      itemBadge: {},
      badgesV2: {},
      ratings: {
        aggregatedRating: {
          rating: "4.3",
          ratingCount: "23 ratings",
          ratingCountV2: "23",
        },
      },
    },
    {
      id: "22034332",
      name: "Solkadhi",
      category: "Beverages",
      description:
        "Solakadhi or kokam kadhi is the most famous digestive drink in malvani cuisine.",
      imageId: "skuyiwtqilxz74zohakz",
      inStock: 1,
      isVeg: 1,
      price: 4500,
      variants: {},
      variantsV2: {},
      itemAttribute: {
        vegClassifier: "VEG",
      },
      ribbon: {},
      showImage: true,
      itemBadge: {},
      badgesV2: {},
      ratings: {
        aggregatedRating: {
          rating: "3.0",
          ratingCount: "3 ratings",
          ratingCountV2: "3",
        },
      },
    },
    {
      id: "33208149",
      name: "Package Drinking Water",
      category: "Beverages",
      inStock: 1,
      isVeg: 1,
      price: 2000,
      variants: {},
      variantsV2: {},
      itemAttribute: {
        vegClassifier: "VEG",
      },
      ribbon: {},
      type: "ITEM",
      itemBadge: {},
      badgesV2: {},
      ratings: {
        aggregatedRating: {},
      },
    },
    {
      id: "33208154",
      name: "Butter Milk",
      category: "Beverages",
      description: "150 ml",
      imageId: "evchlmeh1dnbbqzf9yza",
      inStock: 1,
      isVeg: 1,
      price: 2500,
      variants: {},
      variantsV2: {},
      itemAttribute: {
        vegClassifier: "VEG",
        portionSize: "150 ml",
      },
      ribbon: {},
      showImage: true,
      itemBadge: {},
      badgesV2: {},
      ratings: {
        aggregatedRating: {},
      },
    },
    {
      id: "33208162",
      name: "Lassi",
      category: "Beverages",
      inStock: 1,
      isVeg: 1,
      price: 5000,
      variants: {},
      variantsV2: {},
      itemAttribute: {
        vegClassifier: "VEG",
      },
      ribbon: {},
      type: "ITEM",
      itemBadge: {},
      badgesV2: {},
      ratings: {
        aggregatedRating: {},
      },
    },
    {
      id: "33208166",
      name: "Kokam Sarbat",
      category: "Beverages",
      inStock: 1,
      isVeg: 1,
      price: 2500,
      variants: {},
      variantsV2: {},
      itemAttribute: {
        vegClassifier: "VEG",
      },
      ribbon: {},
      type: "ITEM",
      itemBadge: {},
      badgesV2: {},
      ratings: {
        aggregatedRating: {},
      },
    },
    {
      id: "69951239",
      name: "Thumps Up. - 750ml",
      category: "Beverages",
      inStock: 1,
      isVeg: 1,
      price: 5500,
      variants: {},
      variantsV2: {},
      itemAttribute: {
        vegClassifier: "VEG",
      },
      ribbon: {},
      type: "ITEM",
      itemBadge: {},
      badgesV2: {},
      ratings: {
        aggregatedRating: {},
      },
    },
    {
      id: "69951240",
      name: "Sprite - 750ml",
      category: "Beverages",
      imageId: "yjo2vulcxodktmoagqug",
      inStock: 1,
      isVeg: 1,
      price: 6000,
      variants: {},
      variantsV2: {},
      itemAttribute: {
        vegClassifier: "VEG",
      },
      ribbon: {},
      showImage: true,
      itemBadge: {},
      badgesV2: {},
      ratings: {
        aggregatedRating: {},
      },
    },
  ],
  "Beverage Combos": [
    {
      id: "49900593",
      name: "Ballaleshwar Special Missal Pav + Solkadhi",
      category: "Beverage Combos",
      description:
        "Medium Spicy | Gravy | Serves 1 | Missal pav is a vibrant meal consisting of a spicy sprouted bean curry topped with crunchy farsan, crisp red onions and dahi| Served with one glass of soalkadhi |",
      imageId: "hprx4znac1xklfg3xdnc",
      inStock: 1,
      isVeg: 1,
      price: 14000,
      variants: {},
      variantsV2: {},
      addons: [
        {
          groupId: "15581974",
          groupName: "Addon",
          choices: [
            {
              id: "15651540",
              name: "Lassi",
              price: 4000,
              inStock: 1,
              isVeg: 1,
              isEnabled: 1,
            },
          ],
          maxAddons: -1,
          maxFreeAddons: -1,
        },
      ],
      itemAttribute: {
        vegClassifier: "VEG",
        spiceLevel: "MEDIUMSPICY",
        portionSize: "Serves 1",
      },
      ribbon: {
        text: "Bestseller",
        textColor: "#ffffff",
        topBackgroundColor: "#d53d4c",
        bottomBackgroundColor: "#b02331",
      },
      showImage: true,
      itemBadge: {},
      badgesV2: {},
      isBestseller: true,
      ratings: {
        aggregatedRating: {
          rating: "4.0",
          ratingCount: "5 ratings",
          ratingCountV2: "5",
        },
      },
    },
    {
      id: "49900616",
      name: "Vada Rassa Pav + Solkadhi",
      category: "Beverage Combos",
      imageId: "v9zqtv7q3jm0p2vwk2cm",
      inStock: 1,
      isVeg: 1,
      price: 12500,
      variants: {},
      variantsV2: {},
      itemAttribute: {
        vegClassifier: "VEG",
      },
      ribbon: {},
      showImage: true,
      itemBadge: {},
      badgesV2: {},
      ratings: {
        aggregatedRating: {},
      },
    },
    {
      id: "49900633",
      name: "Kadhi Vada Pav + Solkadhi",
      category: "Beverage Combos",
      imageId: "y76ycxgkobobnmsuxivl",
      inStock: 1,
      isVeg: 1,
      price: 12500,
      variants: {},
      variantsV2: {},
      itemAttribute: {
        vegClassifier: "VEG",
      },
      ribbon: {},
      showImage: true,
      itemBadge: {},
      badgesV2: {},
      ratings: {
        aggregatedRating: {},
      },
    },
  ],
  "Quick Bites": [
    {
      id: "22034318",
      name: "Finger Chips ",
      category: "Quick Bites",
      description: "Medium Spicy",
      imageId: "dndckd3mccvc8augjqyb",
      inStock: 1,
      isVeg: 1,
      price: 6500,
      variants: {},
      variantsV2: {},
      itemAttribute: {
        vegClassifier: "VEG",
        spiceLevel: "MEDIUMSPICY",
      },
      ribbon: {
        text: "Bestseller",
        textColor: "#ffffff",
        topBackgroundColor: "#d53d4c",
        bottomBackgroundColor: "#b02331",
      },
      showImage: true,
      itemBadge: {},
      badgesV2: {},
      isBestseller: true,
      ratings: {
        aggregatedRating: {},
      },
    },
    {
      id: "22034319",
      name: "Baleshwar Special Misal Pav",
      category: "Quick Bites",
      description:
        "Medium Spicy | Serves 1 | A popular maharashtrian delicacy with dry subji topped with flavorsome gravy  | Served with soft pav |",
      imageId: "ftsquc0ng9vpgvj9qmve",
      inStock: 1,
      isVeg: 1,
      price: 10500,
      variants: {},
      variantsV2: {},
      addons: [
        {
          groupId: "3155795",
          groupName: "Add On",
          choices: [
            {
              id: "8619578",
              name: "Extra Pav",
              price: 700,
              inStock: 1,
              isVeg: 1,
              isEnabled: 1,
            },
          ],
          maxAddons: -1,
          maxFreeAddons: -1,
        },
        {
          groupId: "15581976",
          groupName: "Addon",
          choices: [
            {
              id: "30446338",
              name: "Chutney",
              inStock: 1,
              isVeg: 1,
              isEnabled: 1,
            },
            {
              id: "15651540",
              name: "Lassi",
              price: 4000,
              inStock: 1,
              isVeg: 1,
              isEnabled: 1,
            },
          ],
          maxAddons: -1,
          maxFreeAddons: -1,
        },
      ],
      itemAttribute: {
        vegClassifier: "VEG",
        spiceLevel: "MEDIUMSPICY",
        portionSize: "Serves 1",
      },
      ribbon: {
        text: "Bestseller",
        textColor: "#ffffff",
        topBackgroundColor: "#d53d4c",
        bottomBackgroundColor: "#b02331",
      },
      showImage: true,
      itemBadge: {},
      badgesV2: {},
      isBestseller: true,
      ratings: {
        aggregatedRating: {
          rating: "4.0",
          ratingCount: "13 ratings",
          ratingCountV2: "13",
        },
      },
    },
    {
      id: "22034322",
      name: "Moong Bhaji ",
      category: "Quick Bites",
      description: "Medium Spicy",
      imageId: "t1zppi1cs1svvfyg9jsr",
      inStock: 1,
      isVeg: 1,
      price: 6000,
      variants: {},
      variantsV2: {},
      addons: [
        {
          groupId: "43951417",
          groupName: "Addon",
          choices: [
            {
              id: "30446338",
              name: "Chutney",
              inStock: 1,
              isVeg: 1,
              isEnabled: 1,
            },
          ],
          maxAddons: -1,
          maxFreeAddons: -1,
        },
      ],
      itemAttribute: {
        vegClassifier: "VEG",
        spiceLevel: "MEDIUMSPICY",
      },
      ribbon: {
        text: "Bestseller",
        textColor: "#ffffff",
        topBackgroundColor: "#d53d4c",
        bottomBackgroundColor: "#b02331",
      },
      showImage: true,
      itemBadge: {},
      badgesV2: {},
      isBestseller: true,
      ratings: {
        aggregatedRating: {
          rating: "3.8",
          ratingCount: "13 ratings",
          ratingCountV2: "13",
        },
      },
    },
    {
      id: "22034323",
      name: "Kanda Bhaji ",
      category: "Quick Bites",
      description:
        "Medium Spicy | To enjoy mumbai rains you not only need tea but some crispy onions deep fried.",
      imageId: "zwymsqj3260ofnlpx6vk",
      inStock: 1,
      isVeg: 1,
      price: 6000,
      variants: {},
      variantsV2: {},
      itemAttribute: {
        vegClassifier: "VEG",
        spiceLevel: "MEDIUMSPICY",
      },
      ribbon: {
        text: "Bestseller",
        textColor: "#ffffff",
        topBackgroundColor: "#d53d4c",
        bottomBackgroundColor: "#b02331",
      },
      showImage: true,
      itemBadge: {},
      badgesV2: {},
      isBestseller: true,
      ratings: {
        aggregatedRating: {
          rating: "3.2",
          ratingCount: "6 ratings",
          ratingCountV2: "6",
        },
      },
    },
    {
      id: "22034325",
      name: "Vada Rassa Pav",
      category: "Quick Bites",
      description: "Medium Spicy | Gravy",
      imageId: "stba1v60nonjjlsn1ujk",
      inStock: 1,
      isVeg: 1,
      price: 8500,
      variants: {},
      variantsV2: {},
      addons: [
        {
          groupId: "15582000",
          groupName: "Addon",
          choices: [
            {
              id: "15651540",
              name: "Lassi",
              price: 4000,
              inStock: 1,
              isVeg: 1,
              isEnabled: 1,
            },
          ],
          maxAddons: -1,
          maxFreeAddons: -1,
        },
        {
          groupId: "3155798",
          groupName: "Add On",
          choices: [
            {
              id: "8619578",
              name: "Extra Pav",
              price: 700,
              inStock: 1,
              isVeg: 1,
              isEnabled: 1,
            },
          ],
          maxAddons: -1,
          maxFreeAddons: -1,
        },
      ],
      itemAttribute: {
        vegClassifier: "VEG",
        spiceLevel: "MEDIUMSPICY",
      },
      ribbon: {
        text: "Bestseller",
        textColor: "#ffffff",
        topBackgroundColor: "#d53d4c",
        bottomBackgroundColor: "#b02331",
      },
      showImage: true,
      itemBadge: {},
      badgesV2: {},
      isBestseller: true,
      ratings: {
        aggregatedRating: {
          rating: "4.5",
          ratingCount: "13 ratings",
          ratingCountV2: "13",
        },
      },
    },
    {
      id: "22034326",
      name: "Kadhi Vada Pav",
      category: "Quick Bites",
      imageId: "mfceef9paoiso0wr3hia",
      inStock: 1,
      isVeg: 1,
      price: 8500,
      variants: {},
      variantsV2: {},
      addons: [
        {
          groupId: "3155799",
          groupName: "Add On",
          choices: [
            {
              id: "8619578",
              name: "Extra Pav",
              price: 700,
              inStock: 1,
              isVeg: 1,
              isEnabled: 1,
            },
          ],
          maxAddons: -1,
          maxFreeAddons: -1,
        },
        {
          groupId: "15582008",
          groupName: "Addon",
          choices: [
            {
              id: "15651540",
              name: "Lassi",
              price: 4000,
              inStock: 1,
              isVeg: 1,
              isEnabled: 1,
            },
          ],
          maxAddons: -1,
          maxFreeAddons: -1,
        },
      ],
      itemAttribute: {
        vegClassifier: "VEG",
      },
      ribbon: {},
      showImage: true,
      itemBadge: {},
      badgesV2: {},
      ratings: {
        aggregatedRating: {},
      },
    },
    {
      id: "33208177",
      name: "Misal Pav",
      category: "Quick Bites",
      description:
        "Medium Spicy | A popular maharashtrian delicacy with dry subji topped with flavorsome gravy  |Served with soft pav |",
      imageId: "d053dki7gswqgvdihzv1",
      inStock: 1,
      isVeg: 1,
      price: 8500,
      variants: {},
      variantsV2: {},
      addons: [
        {
          groupId: "15581983",
          groupName: "Addon",
          choices: [
            {
              id: "30446338",
              name: "Chutney",
              inStock: 1,
              isVeg: 1,
              isEnabled: 1,
            },
            {
              id: "15651540",
              name: "Lassi",
              price: 4000,
              inStock: 1,
              isVeg: 1,
              isEnabled: 1,
            },
          ],
          maxAddons: -1,
          maxFreeAddons: -1,
        },
      ],
      itemAttribute: {
        vegClassifier: "VEG",
        spiceLevel: "MEDIUMSPICY",
      },
      ribbon: {
        text: "Bestseller",
        textColor: "#ffffff",
        topBackgroundColor: "#d53d4c",
        bottomBackgroundColor: "#b02331",
      },
      showImage: true,
      itemBadge: {},
      badgesV2: {},
      isBestseller: true,
      ratings: {
        aggregatedRating: {
          rating: "4.2",
          ratingCount: "21 ratings",
          ratingCountV2: "21",
        },
      },
    },
  ],
  Desserts: [
    {
      id: "33208158",
      name: "Gulabjam ( 1 Pc )",
      category: "Desserts",
      inStock: 1,
      isVeg: 1,
      price: 1500,
      variants: {},
      variantsV2: {},
      itemAttribute: {
        vegClassifier: "VEG",
      },
      ribbon: {},
      type: "ITEM",
      itemBadge: {},
      badgesV2: {},
      ratings: {
        aggregatedRating: {
          rating: "4.7",
          ratingCount: "3 ratings",
          ratingCountV2: "3",
        },
      },
    },
    {
      id: "58816892",
      name: "Dahivada ( 2 Pcs )",
      category: "Desserts",
      description:
        "Medium Spicy | Dahi vada is a type of chaat originating from the Indian subcontinent and popular throughout south asia. It is prepared by soaking vadas in thick dahi.",
      imageId: "tyevnuupnwlgfzgy4jul",
      inStock: 1,
      isVeg: 1,
      price: 10000,
      variants: {},
      variantsV2: {},
      itemAttribute: {
        vegClassifier: "VEG",
        spiceLevel: "MEDIUMSPICY",
      },
      ribbon: {},
      showImage: true,
      itemBadge: {},
      badgesV2: {},
      ratings: {
        aggregatedRating: {},
      },
    },
  ],
  "Swiggy Exclusive Combos": [
    {
      id: "39327910",
      name: "Misal Pav + Buttermilk",
      category: "Swiggy Exclusive Combos",
      inStock: 1,
      isVeg: 1,
      price: 10500,
      variants: {},
      variantsV2: {},
      addons: [
        {
          groupId: "15582015",
          groupName: "Addon",
          choices: [
            {
              id: "15651540",
              name: "Lassi",
              price: 4000,
              inStock: 1,
              isVeg: 1,
              isEnabled: 1,
            },
          ],
          maxAddons: -1,
          maxFreeAddons: -1,
        },
      ],
      itemAttribute: {
        vegClassifier: "VEG",
      },
      ribbon: {},
      type: "ITEM",
      itemBadge: {},
      badgesV2: {},
      ratings: {
        aggregatedRating: {
          rating: "3.3",
          ratingCount: "3 ratings",
          ratingCountV2: "3",
        },
      },
    },
    {
      id: "39327915",
      name: "Sabudana Vada + Lassi",
      category: "Swiggy Exclusive Combos",
      inStock: 1,
      isVeg: 1,
      price: 11500,
      variants: {},
      variantsV2: {},
      itemAttribute: {
        vegClassifier: "VEG",
      },
      ribbon: {},
      type: "ITEM",
      itemBadge: {},
      badgesV2: {},
      ratings: {
        aggregatedRating: {},
      },
    },
    {
      id: "101293197",
      name: "7 Vada Pav  ",
      category: "Swiggy Exclusive Combos",
      description: "Serves 1",
      inStock: 1,
      isVeg: 1,
      price: 10000,
      variants: {},
      variantsV2: {},
      itemAttribute: {
        vegClassifier: "VEG",
        portionSize: "Serves 1",
      },
      ribbon: {
        text: "Bestseller",
        textColor: "#ffffff",
        topBackgroundColor: "#d53d4c",
        bottomBackgroundColor: "#b02331",
      },
      type: "ITEM",
      itemBadge: {},
      badgesV2: {},
      isBestseller: true,
      ratings: {
        aggregatedRating: {},
      },
    },
  ],
  "Shravan Specials": [
    {
      id: "97887861",
      name: "Sabudana Vada + Lassi   ",
      category: "Shravan Specials",
      inStock: 1,
      isVeg: 1,
      price: 11500,
      variants: {},
      variantsV2: {},
      itemAttribute: {
        vegClassifier: "VEG",
      },
      ribbon: {},
      type: "ITEM",
      itemBadge: {},
      badgesV2: {},
      ratings: {
        aggregatedRating: {},
      },
    },
    {
      id: "97887863",
      name: "Finger Chips + Masala Tea",
      category: "Shravan Specials",
      inStock: 1,
      isVeg: 1,
      price: 6500,
      variants: {},
      variantsV2: {},
      itemAttribute: {
        vegClassifier: "VEG",
      },
      ribbon: {},
      type: "ITEM",
      itemBadge: {},
      badgesV2: {},
      ratings: {
        aggregatedRating: {},
      },
    },
    {
      id: "97887865",
      name: "Sabudana Vada (2 Pcs)  ",
      category: "Shravan Specials",
      description:
        "Medium Spicy | Crispy on the outside, soft on the inside; a deep-fried snack made from sago.",
      inStock: 1,
      isVeg: 1,
      price: 8000,
      variants: {},
      variantsV2: {},
      itemAttribute: {
        vegClassifier: "VEG",
        spiceLevel: "MEDIUMSPICY",
      },
      ribbon: {},
      type: "ITEM",
      itemBadge: {},
      badgesV2: {},
      ratings: {
        aggregatedRating: {
          rating: "4.0",
          ratingCount: "7 ratings",
          ratingCountV2: "7",
        },
      },
    },
  ],
  "Fasting Combo": [
    {
      id: "73002745",
      name: "Sabudana Vada 6 Piece",
      category: "Fasting Combo",
      description: "Sabudana,pinutscrush mirchi, pototo",
      inStock: 1,
      isVeg: 1,
      price: 17500,
      variants: {},
      variantsV2: {},
      itemAttribute: {
        vegClassifier: "VEG",
      },
      ribbon: {},
      type: "ITEM",
      itemBadge: {},
      badgesV2: {},
      ratings: {
        aggregatedRating: {},
      },
    },
  ],
};
